default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy
  password: pointer
development:
  <<: *default
  database: pool-service_development
test:
  <<: *default
  database: pool-service_test
production:
  <<: *default
  database: pool-service_production